/**
 * This code was generated by Builder.io
 */
import React from "react";
import { useAuth } from "../../context/AuthContext";

interface UserDropdownProps {}

const UserDropdown: React.FC<UserDropdownProps> = () => {
  const data=useAuth()
  console.log("data",data)
  return (
    <div className="flex flex-col self-stretch my-auto w-10"
    onClick={()=>{
      data.logout()
    }}>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/6d26eb0bd0e6c26918d1a5b803a347892b2c279b347d2d74c7fd0667d1503c18?placeholderIfAbsent=true&apiKey=de20ebe5f7e54554b52c3c72396947ee"
        alt="User profile"
        className="object-contain w-10 aspect-square min-h-[40px] rounded-[200px]"
      />
    </div>
  );
};

export default UserDropdown;
