/**
 * This code was generated by Builder.io
 */
import React from "react";

interface ActivePatientsProps {}

const ActivePatients: React.FC<ActivePatientsProps> = () => {
  return (
    <div data-layername="section" className="flex flex-col w-60">
      <div
        data-layername="sectionHeader"
        className="flex flex-col pb-px w-full"
      >
        <div data-layername="content" className="flex gap-4 items-start w-full">
          <h2
            data-layername="text"
            className="flex-1 shrink text-lg font-medium leading-loose text-gray-900 basis-0"
          >
            Active Patients
          </h2>
          <div data-layername="actions" className="flex gap-3 items-center w-5">
            <div
              data-layername="dropdown"
              className="flex flex-col self-stretch my-auto w-5"
            >
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/553303d68d29ce6c746e13f635dd945e051cb59baa889c39c49940e225391b16?placeholderIfAbsent=true&apiKey=de20ebe5f7e54554b52c3c72396947ee"
                alt=""
                className="object-contain w-full aspect-square"
              />
            </div>
          </div>
        </div>
        <div
          data-layername="divider"
          className="flex mt-5 w-full bg-gray-200 min-h-[1px]"
        />
      </div>
      <div
        data-layername="activityGauge"
        className="flex gap-4 items-start mt-6 w-60 max-w-full text-3xl font-semibold leading-none text-center text-gray-900 whitespace-nowrap"
      >
        <div data-layername="activitiyGauge" className="flex flex-col w-60">
          <div className="flex relative flex-col justify-center p-5 w-full aspect-square">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/5d737d8318ed8d4e35e6a7d9f4906e4b6ce05fd189f8dae0949f5ec2e5b6c854?placeholderIfAbsent=true&apiKey=de20ebe5f7e54554b52c3c72396947ee"
              alt=""
              className="object-cover absolute inset-0 size-full"
            />
            <div className="flex relative flex-col justify-center p-5 aspect-square w-[200px]">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/6a3ca0e55eda76e95c5e811591bd1a530345e61df1e671707b319d8903268025?placeholderIfAbsent=true&apiKey=de20ebe5f7e54554b52c3c72396947ee"
                alt=""
                className="object-cover absolute inset-0 size-full"
              />
              <div className="flex relative flex-col px-14 py-16 aspect-square max-md:px-5">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/d48fc5378c4503eecf863708afea4d3b11ba1335c07c35d23577c44851afc506?placeholderIfAbsent=true&apiKey=de20ebe5f7e54554b52c3c72396947ee"
                  alt=""
                  className="object-cover absolute inset-0 size-full"
                />
                316
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ActivePatients;
