/**
 * This code was generated by Builder.io
 */
import React from "react";
import ActivePatients from "./ActivePatients";
import TotalPatients from "./TotalPatients";
import PatientsTable from "./PatientsTable";

interface MainContentProps {}

const Dashboard: React.FC<MainContentProps> = () => {
  return (
<div>
        <section
          data-layername="section"
          className="flex flex-col w-full max-md:max-w-full"
        >
          <div
            data-layername="container"
            className="flex flex-wrap gap-10 items-start w-full max-md:px-5 max-md:max-w-full"
          >
            <ActivePatients />
            <TotalPatients />
          </div>
        </section>
        <PatientsTable />
      </div>
  );
};

export default Dashboard;