/**
 * This code was generated by Builder.io
 */
import React from "react";
import { Link, useLocation } from "react-router-dom";

interface NavItemProps {
  src: string;
  active: boolean;
  pageName?: string;
}

const NavItem: React.FC<NavItemProps> = ({ src, pageName }) => {
  const location = useLocation();
  return (
    <div
      data-layername="navItemButton"
      onClick={() => {}}
      className={`flex overflow-hidden gap-10 items-center p-3 mt-2 w-12 h-12 ${
        location.pathname.startsWith('/'+pageName) ? "bg-blue-600" : "bg-blue-700"
      } rounded-md`}
    >
      <Link to={`/${pageName}`}>
        <img
          loading="lazy"
          src={src}
          alt=""
          className="object-contain w-6 aspect-square"
        />
      </Link>
    </div>
  );
};

export default NavItem;
