/**
 * This code was generated by Builder.io
 */
import React from 'react';
import TableHeader from './TableHeader';
import TableRow from './TableRow';

interface PatientsTableProps {}

const PatientsTable: React.FC<PatientsTableProps> = () => {
  const patients = [
    { name: 'Catalog', website: 'catalogapp.io', status: 'Customer', symptoms: 24, about: 'Content curating app', description: 'Brings all your news into one place' },
    { name: 'Circooles', website: 'getcirooles.com', status: 'Churned', symptoms: 85, about: 'Design software', description: 'Super lightweight design app' },
    { name: 'Command+R', website: 'cmdr.ai', status: 'Customer', symptoms: 52, about: 'Data prediction', description: 'AI and machine learning data' },
    // Continuing from where we left off:

    { name: 'Hourglass', website: 'hourglass.app', status: 'Customer', symptoms: 0, about: 'Productivity app', description: 'Time management and productivity' },
    { name: 'Layers', website: 'getlayers.io', status: 'Churned', symptoms: 10, about: 'Web app integrations', description: 'Connect web apps seamlessly' },
    { name: 'Quotient', website: 'quotient.co', status: 'Customer', symptoms: 29, about: 'Sales CRM', description: 'Web-based sales doc management' },
    { name: 'Sisyphus', website: 'sisyphus.com', status: 'Customer', symptoms: 63, about: 'Automation and workflow', description: 'Time tracking, invoicing and expenses' },
  ];

  return (
    <section data-layername="section" className="flex flex-col mt-8 w-full max-md:max-w-full">
      <div data-layername="container" className="flex flex-col px-8 w-full max-md:px-5 max-md:max-w-full">
        <div data-layername="filtersBar" className="flex gap-4 items-start w-full rounded-lg max-md:max-w-full">
          <div data-layername="content" className="flex flex-wrap flex-1 shrink gap-4 items-center w-full basis-0 min-w-[240px] max-md:max-w-full">
            <div data-layername="dropdowns" className="flex flex-wrap flex-1 shrink gap-3 items-start self-stretch my-auto text-sm font-semibold leading-none basis-0 min-w-[240px] text-slate-700 max-md:max-w-full">
              <button data-layername="button" className="flex items-start rounded-lg">
                <div data-layername="buttonBase" className="flex overflow-hidden gap-2 justify-center items-center px-4 py-2.5 bg-white rounded-lg border border-gray-300 border-solid shadow-sm">
                  <span data-layername="text" className="self-stretch my-auto">All time</span>
                  <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/ca3735c52cb7a0b5e64f5c2146fc38c5e328df911b69a777314c7adb4f9dce2d?placeholderIfAbsent=true&apiKey=de20ebe5f7e54554b52c3c72396947ee" alt="" className="object-contain shrink-0 self-stretch my-auto w-5 aspect-square" />
                </div>
              </button>
              <button data-layername="button" className="flex items-start rounded-lg">
                <div data-layername="buttonBase" className="flex overflow-hidden gap-2 justify-center items-center px-4 py-2.5 bg-white rounded-lg border border-gray-300 border-solid shadow-sm">
                  <span data-layername="text" className="self-stretch my-auto">US, AU, +4</span>
                  <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/ca3735c52cb7a0b5e64f5c2146fc38c5e328df911b69a777314c7adb4f9dce2d?placeholderIfAbsent=true&apiKey=de20ebe5f7e54554b52c3c72396947ee" alt="" className="object-contain shrink-0 self-stretch my-auto w-5 aspect-square" />
                </div>
              </button>
              <button data-layername="button" className="flex items-start rounded-lg">
                <div data-layername="buttonBase" className="flex overflow-hidden gap-2 justify-center items-center px-4 py-2.5 bg-white rounded-lg border border-gray-300 border-solid shadow-sm">
                  <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/565ef0f7d60ee4cafb3e62c36e3f2b725be54df8b71e3b1813ba0884d857d57b?placeholderIfAbsent=true&apiKey=de20ebe5f7e54554b52c3c72396947ee" alt="" className="object-contain shrink-0 self-stretch my-auto w-5 aspect-square" />
                  <span data-layername="moreFilters" className="self-stretch my-auto">More filters</span>
                </div>
              </button>
            </div>
            <form data-layername="inputDropdown" className="flex flex-col self-stretch my-auto w-80 text-base text-gray-500 whitespace-nowrap min-w-[240px]">
              <div data-layername="inputDropdownBase" className="flex flex-col">
                <div data-layername="inputWithLabel" className="flex flex-col w-full">
                  <div data-layername="input" className="flex gap-2 items-center px-3.5 py-2.5 w-full bg-white rounded-lg border border-gray-300 border-solid shadow-sm">
                    <div data-layername="content" className="flex flex-1 shrink gap-2 items-center self-stretch my-auto w-full basis-0 min-w-[240px]">
                      <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/ce8f75f9fac46ea9c19d721687c414b5591f8f309e14174308b5cec679370a87?placeholderIfAbsent=true&apiKey=de20ebe5f7e54554b52c3c72396947ee" alt="" className="object-contain shrink-0 self-stretch my-auto w-5 aspect-square" />
                      <input type="search" placeholder="Search" aria-label="Search" className="flex-1 bg-transparent border-none outline-none" />
                    </div>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
        <div data-layername="table" className="flex overflow-hidden flex-col mt-6 w-full bg-white rounded-lg border border-gray-200 border-solid shadow-md max-md:max-w-full">
          <div data-layername="content" className="flex flex-wrap items-start w-full bg-white max-md:max-w-full">
            <TableHeader />
            {patients.map((patient, index) => (
              <TableRow key={index} patient={patient} />
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};

export default PatientsTable;