/**
 * This code was generated by Builder.io
 */
import React from "react";

interface TableHeaderProps {}

const TableHeader: React.FC<TableHeaderProps> = () => {
  return (
    <>
      <div
        data-layername="column"
        className="flex flex-col flex-1 shrink basis-0 min-w-[240px] max-md:max-w-full"
      >
        <div
          data-layername="tableHeaderCell"
          className="flex gap-3 items-center px-6 py-3 w-full bg-gray-50 border-b border-solid border-b-gray-200 min-h-[44px] max-md:px-5 max-md:max-w-full"
        >
          <div
            data-layername="checkbox"
            className="flex justify-center items-center self-stretch my-auto w-5"
          >
            <input type="checkbox" className="w-5 h-5 rounded-md" />
          </div>
          <div
            data-layername="tableHeader"
            className="flex gap-1 items-center self-stretch my-auto text-xs font-medium text-gray-500 whitespace-nowrap"
          >
            <span data-layername="text" className="self-stretch my-auto">
              Patients
            </span>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/c5d7001643d307f14a4962eb289ab9ae7f8dbc9184e760d7bf2238614bf8a11f?placeholderIfAbsent=true&apiKey=de20ebe5f7e54554b52c3c72396947ee"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-4 aspect-square"
            />
          </div>
        </div>
      </div>
      <div
        data-layername="column"
        className="flex flex-col text-xs font-medium text-emerald-700 whitespace-nowrap w-[121px]"
      >
        <div
          data-layername="tableHeaderCell"
          className="flex gap-3 items-center px-6 py-3 py-3.5 w-full text-gray-500 bg-gray-50 border-b border-solid border-b-gray-200 min-h-[44px] max-md:px-5"
        >
          <div
            data-layername="tableHeader"
            className="gap-1 self-stretch my-auto"
          >
            Status
          </div>
        </div>
      </div>
      <div data-layername="column" className="flex flex-col w-44">
        <div
          data-layername="tableHeaderCell"
          className="flex gap-3 items-center px-6 py-3 py-3.5 w-full text-xs font-medium text-gray-500 bg-gray-50 border-b border-solid border-b-gray-200 min-h-[44px] max-md:px-5"
        >
          <div
            data-layername="tableHeader"
            className="gap-1 self-stretch my-auto"
          >
            Symptoms
          </div>
        </div>
      </div>
      <div
        data-layername="column"
        className="flex flex-col text-sm min-w-[240px] w-[301px]"
      >
        <div
          data-layername="tableHeaderCell"
          className="flex gap-3 items-center px-6 py-3 py-3.5 w-full text-xs font-medium text-gray-500 whitespace-nowrap bg-gray-50 border-b border-solid border-b-gray-200 min-h-[44px] max-md:px-5"
        >
          <div
            data-layername="tableHeader"
            className="gap-1 self-stretch my-auto"
          >
            About
          </div>
        </div>
      </div>
      <div
        data-layername="column"
        className="flex flex-col text-sm min-w-[240px] w-[301px]"
      >
        <div
          data-layername="tableHeaderCell"
          className="flex gap-3 items-center px-6 py-3 py-3.5 w-full text-xs font-medium text-gray-500 whitespace-nowrap bg-gray-50 border-b border-solid border-b-gray-200 min-h-[44px] max-md:px-5"
        >
          <div
            data-layername="tableHeader"
            className="gap-1 self-stretch my-auto"
          >
            About
          </div>
        </div>
      </div>
      <div
        data-layername="column"
        className="flex flex-col text-sm min-w-[240px] w-[301px]"
      >
        <div
          data-layername="tableHeaderCell"
          className="flex gap-3 items-center px-6 py-3 py-3.5 w-full text-xs font-medium text-gray-500 whitespace-nowrap bg-gray-50 border-b border-solid border-b-gray-200 min-h-[44px] max-md:px-5"
        >
          <div
            data-layername="tableHeader"
            className="gap-1 self-stretch my-auto"
          >
            About
          </div>
        </div>
      </div>
      <div data-layername="column" className="flex flex-col w-[116px]">
        <div
          data-layername="tableHeaderCell"
          className="flex gap-3 px-6 py-3 w-full bg-gray-50 border-b border-solid border-b-gray-200 min-h-[44px]"
        />
      </div>
    </>
  );
};

export default TableHeader;
