/**
 * This code was generated by Builder.io
 */
import React from "react";

interface TotalPatientsProps {}

const TotalPatients: React.FC<TotalPatientsProps> = () => {
  return (
    <div
      data-layername="section"
      className="flex flex-col flex-1 shrink basis-0 min-w-[240px] max-md:max-w-full"
    >
      <div
        data-layername="sectionHeader"
        className="flex flex-col pb-px w-full max-md:max-w-full"
      >
        <div
          data-layername="content"
          className="flex flex-wrap gap-4 items-start w-full max-md:max-w-full"
        >
          <h2
            data-layername="text"
            className="flex-1 shrink text-lg font-medium leading-loose text-gray-900 basis-0 max-md:max-w-full"
          >
            Total Patients
          </h2>
          <div data-layername="actions" className="flex gap-3 items-center w-5">
            <div
              data-layername="dropdown"
              className="flex flex-col self-stretch my-auto w-5"
            >
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/be32e70f3a4049e60955556305b6788bbf34fbd20a4a2a296fc3663632f6159d?placeholderIfAbsent=true&apiKey=de20ebe5f7e54554b52c3c72396947ee"
                alt=""
                className="object-contain w-full aspect-square"
              />
            </div>
          </div>
        </div>
        <div
          data-layername="divider"
          className="flex mt-5 w-full bg-gray-200 min-h-[1px] max-md:max-w-full"
        />
      </div>
      <div className="flex flex-col mt-6 w-full max-md:max-w-full">
        <div data-layername="axis" className="flex gap-1 min-h-[240px]">
          <div
            data-layername="content"
            className="flex flex-col flex-1 shrink w-full basis-0 min-w-[240px] max-md:max-w-full"
          >
            <div
              data-layername="legend"
              className="flex gap-3.5 items-start self-end text-sm leading-none text-gray-500 whitespace-nowrap"
            >
              <div
                data-layername="legendSeries"
                className="flex gap-2 items-center"
              >
                <div
                  data-layername="color"
                  className="flex shrink-0 self-stretch my-auto w-2 h-2 bg-indigo-300 rounded-full"
                />
                <div data-layername="series1" className="self-stretch my-auto">
                  2021
                </div>
              </div>
              <div
                data-layername="legendSeries"
                className="flex gap-2 items-center"
              >
                <div
                  data-layername="color"
                  className="flex shrink-0 self-stretch my-auto w-2 h-2 bg-blue-400 rounded-full"
                />
                <div data-layername="series2" className="self-stretch my-auto">
                  2020
                </div>
              </div>
              <div
                data-layername="legendSeries"
                className="flex gap-2 items-center"
              >
                <div
                  data-layername="color"
                  className="flex shrink-0 self-stretch my-auto w-2 h-2 bg-blue-700 rounded-full"
                />
                <div data-layername="series3" className="self-stretch my-auto">
                  2019
                </div>
              </div>
            </div>
            <div
              data-layername="yAxis"
              className="flex flex-col flex-1 justify-between w-full max-md:max-w-full"
            >
              {[...Array(6)].map((_, index) => (
                <div
                  key={index}
                  data-layername="yAxisLine"
                  className={`flex gap-2 items-center ${
                    index > 0 ? "mt-5" : ""
                  } w-full min-h-[17px] max-md:max-w-full`}
                >
                  <div
                    data-layername="divider"
                    className="flex-1 shrink self-stretch my-auto w-full bg-gray-100 border border-gray-100 border-solid basis-0 min-h-[1px] min-w-[240px] max-md:max-w-full"
                  />
                </div>
              ))}
            </div>
            <div
              data-layername="xAxis"
              className="flex flex-wrap gap-10 justify-between items-center px-6 w-full text-xs text-center text-gray-500 whitespace-nowrap max-md:px-5 max-md:max-w-full"
            >
              {[
                "Jan",
                "Feb",
                "Mar",
                "Apr",
                "May",
                "Jun",
                "Jul",
                "Aug",
                "Sep",
                "Oct",
                "Nov",
                "Dec",
              ].map((month) => (
                <div
                  key={month}
                  data-layername={month.toLowerCase()}
                  className="self-stretch my-auto"
                >
                  {month}
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TotalPatients;
